import "./globals.css";
import { Space_Mono } from "next/font/google";

const mainFont = Space_Mono({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata = {
  title: "Area96, where creatives thrive.",
  description: "Generated by create next app",
  icons: {
    icon: "/96_logo.png",
  },
};

export default ({ children }) => {
  return (
    <html lang="en" className={`${mainFont.className} bg-green-400`}>
      <body>{children}</body>
    </html>
  );
};
